env: dev

datasource:
  username: root
  password:
  url: jdbc:mysql://localhost:3306/helphim?useUnicode=true&characterEncoding=UTF-8
  driverClass: com.mysql.jdbc.Driver

uploadFile:
  prefix: src/main/resources/static/uploadImg/